#     _____               _ _____  _             _
#    / ____|             | |  __ \| |           | |
#   | (___   ___  ___  __| | |__) | | __ _ _ __ | |_ ___ _ __
#    \___ \ / _ \/ _ \/ _` |  ___/| |/ _` | '_ \| __/ _ \ '__|
#    ____) |  __/  __/ (_| | |    | | (_| | | | | ||  __/ |
#   |_____/ \___|\___|\__,_|_|    |_|\__,_|_| |_|\__\___|_|
#
#
# USAGE:
# items:
#   "id:meta"      YOU CAN JUST PUT THE ID IF YOU WANT TO USE ALL DAMAGE -> Exemple, the diamond hoe
#      radius: RADIUS
#      potato: true|false
#      carrot: true|false
#      beetroot: true|false
#      wheat: true|false
#      pumpkin: true|false
#      melon: true|false
#      netherwart: true|false

items:
  "294":
    "radius": 5
    "potato": true
    "carrot": true
    "beetroot": true
    "wheat": true
    "pumpkin": true
    "melon": true
    "netherwart": true
